from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('',views.home),
    path('login/',views.user),
    path('register/',views.puser),
    path('adminhome/',views.adminhome),
    path('admanageplace/',views.manage),
    path('update/<id>',views.updatema),
    path('delete/<id>',views.deletema),
    path('admanadept/',views.depmanage),
    path('updatee/<id>',views.updatedp),
    path('deletee/<id>',views.deletedp),
    path('publichome/',views.phome),
    path('adviewpub/',views.viewpub),
    path('depthome/',views.deptho),
    # path('depviewcompl/',views.deptcom),
    path('viewreview/',views.viewreview),
    path('manrules/',views.rules),
    path('updated/<id>',views.updateru),
    path('deleted/<id>',views.deleteru),
    path('viewrules/',views.viewrules),
    path('viewdept/',views.viewdepte),
    path('activity/<id>',views.activi),
    path('publicrating/<id>',views.rating),
    path('upadtedd/<id>',views.updaterate),
    path('deletededd/<id>',views.deleterate),
    path('viewpubli/',views.viewcomplaint),
    path('adminmessage/<id>',views.message),
    path('deletemssg/<id>',views.deleteemsg),
    path('viewmessage/',views.viewmessagee),
    path('managestaff/',views.staff),
    path('updatei/<id>',views.updatesta),
    path('deletei/<id>',views.deletesta),
    path('staffhome/',views.staffHome),
    path('depviewcompl/',views.viewcompre),
    path('reply/<int:id>/', views.reply),
    path('manageactivity/',views.manageact),
    path('updatii/<id>',views.updateact),
    path('deletii/<id>',views.deleteact),
    path('deprate/',views.viewrate),
    path('deptviewmsg/',views.deptviewmsgeee),
    path('stviewrate/',views.staffreview),
    path('staffcomp/',views.staffcomplaints),
    path('staffviewact/',views.viewactivity),
    path('pubviewact/',views.pviewact),
    path('addwork/',views.addwork),
    path('uploadwork/<id>',views.viewupload),
    path('updatefile/<id>',views.updatefile),
    path('deletefile/<id>',views.deletefile),
    path('viewworkstaf/',views.viewstaffwork),
    path('postcomp/<id>',views.postcompp),
    path('updatecom/<id>',views.upcom),
    path('deletecom/<id>',views.delecom),
    path('uploaddimg/<id>',views.img),
    path('updateimg/<id>',views.updateimg),
    path('deleteimg/<id>',views.deleimg),  
    path('vius/',views.vius),
    path('departmsg/<id>',views.msg),
  
    path('deletemsg/<id>',views.deletemsg),

    path('de/',views.dpmsg),
    path('viewworkdept/<wd>/<st>',views.viewworkde),
    
    path('adsolve/',views.adsolve),
    path('upadted/<id>',views.upadd),
    path('deleteded/<id>',views.deleadd),    
    path('publicmsgview/',views.publicviewmsgeee),
  
    
]
